title: Kuba Andrýsek
# subtitle: Moje projekty
description: >- # this means to ignore newlines until "baseurl:"
  Jmenuji se Jakub Andrýsek, ale všichni mi říkají Kubo. Jsem programátor, 3D modelář a elektronik v Robotárně.

url: "https://kubaandrysek.cz" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    # - text: O mě
    #   url: /about
    - text: Projekty
      url: /projekty/
    - text: Blog
      url: /blog/
    # - text: Galerie
    #   url: /gallery
    - text: Kontakt
      url : /kontakt/
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit these details

author_logo: profile.png
author: Kuba Andrýsek
author_bio: Jmenuji se Jakub Andrýsek, ale všichni mi říkají Kubo. Jsem programátor, 3D modelář a elektronik v Robotárně.
author_email: "email@kubaandrysek.cz"
author_location: Česká republika - Brno
author_website_url: "https://kubaandrysek.cz"


# Choose what to show ( can be true or false)
show_author_work_experiences: true
author_work_experiences:
            - designation: Dvě první místa na robotickém dni v Praze
              company_name: červen 2019
              description: V kategoriích Toy Cleanup a Roadside Assistance
              company_logo: medvedice.jpg
              company_url: http://robotickyden.cz                        
              visibility: true
            - designation: 1. místo v programátorské soutěži
              company_name: březen 2019
              description: 
              company_logo: code.png
              company_url: 
              visibility: true

show_author_education_details: true
author_education_details:
              - college_logo: gvid.jpg
                college_name: Gymnázium Brno, Vídeňská, příspěvková organizace
                college_url: http://www.gvid.cz
                description: Šestileté gymnázium zaměřené na informatiku
                visibility: true

# Setup for page projekty-categories
# Which categories are displayed on page projekty
# It depends on the order
show_author_project_details: true
projects:
      - IoT
      - Roboruka
      - Laser
      - 3D-tisk
      - SLA
      - Helceletka
      - Návody
      - Lezčata
      - Rotex

# projects:
#       - IoTIoT
#       - roboruka      

# social links
# twitter_username: johndoe
github_username:  JakubAndrysek
# facebook_username: johndoe
linkedin_username: jakub-andrysek
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe


#for comments using disqus
disqus_shortname: kuba-andrysek

# wakatime username (coding activity)
wakatime_username: KubaAndrysek

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_form_id: xpzorajw

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-149505692-2



# algolia search
# algolia:
#   application_id: XH3020M2M2 #D9WA1YKTRQ
#   index_name: blog_posts # You can replace that with whatever name you want
#   files_to_exclude: []
#   nodes_to_index: 'article'
#   search_only_api_key: e2d65805318c9e4170af258817cdddbd #58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 6
per_page: 6
paginate_path: "/blog/page/:num/"

permalink: /:year/:month/:day/:title:output_ext

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


highlighter: rouge

# Gallery
# defaults:
#   -
#     scope:
#       path: "gallery"
#     values:
#       permalink: /:path/:basename:output_ext

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build