title: Kuba Andrýsek

# url: "https://kubaandrysek.cz"
url: "localhost:4000"
#url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Projects
      url: /projects/
    - text: Blog
      url: /blog/
    - text: Equipment
      url: /equipment/
    - text: Contact
      url : /contact/

author: Kuba Andrýsek
author_email: "email@kubaandrysek.cz"
author_location: Czech Republic - Brno
author_location_cs: Česká republika - Brno
author_website_url: "https://kubaandrysek.cz"

# image 100x100px
author_work_experiences:
  - designation: Organization of the Largest Robotics Competition in Czech Republic - Robotiáda (Technical Part)
    date: February 2023
    description: I held the position of technical guarantor at the competition.
    company_logo: work_experiences/robotiada23.jpg
    company_url: https://robotiada.cz
  - designation: Presentation of SOČ at an international conference in Luxembourg
    date: October 2022
    description: Expo-Sciences Luxembourg 2022 Conference
    company_logo: work_experiences/lucembursko.jpg
    company_url: https://stisk.online/a/iib4p/davat-sanci-mladym-lidem-ma-smysl-rika-student-jakub-andrysek
  - designation: Jaroslav Heyrovský Foundation Fund Award
    date: December 2021
    description: For successful work on SOČ
    company_logo: work_experiences/heyrovsky.png
    company_url: http://www.njh.cz/laureati-2021
  - designation: Nominated for international competitions
    date: September 2021
    description: Electro category
    company_logo: work_experiences/mezinarod.jpg
  - designation: 1st place in the regional round of SOČ
    date: May 2021
    description: Electro category
    company_logo: work_experiences/soc21.png
    company_url: https://youtu.be/9FYx6xdfJAo

author_work_experiences_more:
  - designation: 4th place in the national round of SOČ
    date: June 2021
    description: Electro category
    company_logo: work_experiences/pletarna.png
    company_url: https://youtu.be/9FYx6xdfJAo
  - designation: 2nd place in the regional round of microchip programming competition
    date: April 2021
    description:
    company_logo: work_experiences/mikro21.png
    company_url:
  - designation: Two first places at Robotics Day in Prague
    date: June 2019
    description: In Toy Cleanup and Roadside Assistance categories
    company_logo: work_experiences/medvedice.jpg
    company_url: http://robotickyden.cz
  - designation: 1st place in programming competition
    date: March 2019
    description:
    company_logo: work_experiences/code.png
    company_url:


show_author_education_details: true
author_education_details:
  - college_logo: education/gvid.jpg
    college_name: Gymnázium Brno, Vídeňská, příspěvková organizace
    college_url: http://www.gvid.cz
    description: Six-year grammar school focused on informatics
    visibility: true

# Setup for page projekty-categories
# Which categories are displayed on page projekty
# It depends on the order
show_author_project_details: true
projects:
  - IoT
  - MacBook
  - Rotex
  - Helceletka
  - Programování
  - Roboruka
  - Laser
  - 3D-tisk
  - Elektro
  - SLA
  - Návody
  - Lezčata

# social links
github_username:  JakubAndrysek
github_username_sponsor:  JakubAndrysek
linkedin_username: jakub-andrysek
twitter_username: Jakubandrysek1
# facebook_username: johndoe
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe
scholar_username: UBOvUgkAAAAJ


#for comments using disqus
disqus_shortname: kuba-andrysek

# wakatime username (coding activity)
wakatime_username: KubaAndrysek

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_form_id: xpzorajw

# syntax highlighter
markdown: kramdown
highlighter: rouge
#permalink: pretty

kramdown:
  input: GFM

# google analytics
google_analytics: G-FN9VPDQRLV

# pagination of posts
paginate: 6
per_page: 6
paginate_path: "/blog/page/:num/"

permalink: /:year/:month/:day/:title

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-redirect-from
#  - jekyll-target-blank


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build